name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      # https://github.com/golangci/golangci-lint-action?tab=readme-ov-file#how-to-use
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: v1.57
